# Question

The component below makes a mistake when using `useEffect`. When running this code, we will get an error from React! 

What is the mistake? Also, please demonstrate how to properly fetch by fixing this code.

```js
const DogDisplay = () => {
  const [imgSrc, setImgSrc] = useState('https://images.dog.ceo/breeds/hound-english/n02089973_612.jpg');

  useEffect(async () => {
    try {
      const response = await fetch('https://dog.ceo/api/breeds/image/random');
      if (!response.ok) throw new Error(`Error: ${response.status}`)
      const data = await response.json();
      setImgSrc(data.message);
    } catch (error) {
      console.error(error);
    }
  }, []);

  return <img src={imgSrc} />
}
```

# Answer
You cannot make the callback function in useEffect asynchronous itself; The callback function has to be a synchronous function that initializes and immediately calls an asynchronous function inside of it. Instead you should make the fetch function in a separate file and import it. Then useEffect will run that function and will receive either the data or error.

# Teacher Feedback
